version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: googleapis
    versions:
    - 67.0.0
    - 67.1.0
    - 67.1.1
    - 68.0.0
    - 70.0.0
    - 71.0.0
    - 72.0.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: mailparser
    versions:
    - 3.0.1
    - 3.1.0
    - 3.2.0
  - dependency-name: "@hapi/boom"
    versions:
    - 9.1.1
    - 9.1.2
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: eslint-config-salesflare
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: "@hapi/wreck"
    versions:
    - 17.1.0
